stages:
  fetch_mongo_data:
    cmd: python src\hap\mongodb_datafetch.py

    deps:
      - src\hap\mongodb_datafetch.py
      - config\config.yml
    outs:
      - artifacts\data_ingestion\raw.csv
      - dvc remote\raw.csv

      