name : 'Heart Attack Prediction'
version: 1.0.0
config_version: 1


artifacts_root : artifacts

data_ingestion: 
  root_dir: artifacts/data_ingestion
  raw_data_path : artifacts/data_ingestion

dvc_remote:
  remote_dir: dvc remote