name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: linux
    
    strategy:
      matrix:
        python-version: [3.8.0]
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  deploy:
    needs: build
    name: Deploy to Render
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:        
        render-token: ${{ secrets.RENDER_TOKEN }}
        service-id: ${{ secrets.SERVICE_ID }}
        retries: 20
        wait: 16000
        sleep: 30000
